### ISSUE TITLE
Incorrect times appearing on ui (probably) because of GMT offset

### ISSUE THREAD

**Issue by krasatos** [kloggy/Home-Assistant#2]
Hey there, 
I noticed that although the schedules would fire at the correc time (set at the input_time), The indicated "Next Scheduled Run Time" was +3h.
I imagined that it was due to GMT offset of Greece (where i am) and (i am also wildly gessing here) the fact that you use `timestamp` in the code which get unix timestamp(?)

AAnyways, here's how i fixed but you will probably come up with a far better way:
original `garden_globals.yaml`:
```
      cycle1_next_run_time:
        friendly_name: "Next scheduled run time"
        value_template: >
          {% if is_state('input_boolean.cycle1_enable', 'on') %}
            {{ state_attr('input_datetime.cycle1_next_run_time', 'timestamp') | timestamp_custom("%a %d %h at %H:%M") }}
          {% else %}
            None
          {% endif %}

      cycle2_next_run_time:
        friendly_name: "Next scheduled run time"
        value_template: >
          {% if is_state('input_boolean.cycle2_enable', 'on') %}
            {{ state_attr('input_datetime.cycle2_next_run_time', 'timestamp') | timestamp_custom("%a %d %h at %H:%M") }}
          {% else %}
            None
          {% endif %}
```

modified `garden_globals.yaml`:
```
      cycle1_next_run_time:
        friendly_name: "Next scheduled run time"
        value_template: >
          {% if is_state('input_boolean.cycle1_enable', 'on') %}
            {{ (state_attr('input_datetime.cycle1_next_run_time', 'timestamp') | int + (60*60*-3)) | timestamp_custom("%a %d %h at %H:%M") }}
          {% else %}
            None
          {% endif %}

      cycle2_next_run_time:
        friendly_name: "Next scheduled run time"
        value_template: >
          {% if is_state('input_boolean.cycle2_enable', 'on') %}
            {{ (state_attr('input_datetime.cycle2_next_run_time', 'timestamp') | int + (60*60*-3)) | timestamp_custom("%a %d %h at %H:%M") }}
          {% else %}
            None
          {% endif %}

```
I actually opened a parenthesis before `state_attr` and added `| int + (60*60*-3))` after the `...,'timestamp')` to fix my time difference.
Again, this does not affect the start-times just the indicated ones.

**Comment by kloggy** [comment]
Same apology for the late reply!!

I'll be honest, UNIX date and times are not my strong point! I don't come form a UNIX background so I find every time I want to do something with dates and times I have to look up how to do it again. I suspect you are right about the +3h due to GMT but I am sure there must be a way I could have coded it to make it automatically correct.....
