### ISSUE TITLE
Add support for moisture sensors on zones

### ISSUE THREAD

**Issue by ocalvo** [kloggy/Home-Assistant#3]
I have ZigBee moisture sensors deep in the ground by PlaidSystems.
I will be nice to skip a zone if the sensors detects enough water (above 26%) in the ground.

**Comment by kloggy** [comment]
Hey! sorry, I only just saw this, I don't know why I didn't get a notification...

I don't have moisture sensors so I don't think this something I would implement. It does sound like it might be something that wouldn't be to hard to do though.

Off the top of my head, in `script.calculate_adjusted_zone_durations`, the last thing you do could be to change the value to zero if your moisture sensors show 26% or more?

Again, sorry for the slow response.

**Comment by ocalvo** [comment]
Why was this closed?

**Comment by kloggy** [comment]
Sorry I just thought there was nothing to add. I'm more than happy to open it again if you want.
But please bear in mind that as I say in the readme this isn't really a GitHub repository in the truest sense, I just used it as a place to simply share my code as I got a few request on the forum to do so.
